Move build to root folder, include both `dumper` and `client` tools
google/dwh-migration-tools pull request #11
Opened 2022-05-19 09:55 UTC by paolomorandini

The intention is to have the same commands perform the same actions whether they are executed in the repository top-level folder or in the unzipped archive top-level folder

Test archive:
```
./gradlew :publishedDistZip
unzip build/distributions/dwh-migration-tools.zip
cd dwh-migration-tools
bin/bin/dwh-migration-dumper --help # invoke with meaningful args
bin/dwh-migration-client --help # invoke with meaningful args
```

Test repository:
```
bin/bin/dwh-migration-dumper --help # invoke with meaningful args
bin/dwh-migration-client --help # invoke with meaningful args
```

Both are expected to have the same behavior.

2022-05-19 13:12 UTC, paolomorandini commented on dumper/lib-dumper-spi/build.gradle
> +	implementation "com.fasterxml.jackson.core:jackson-databind"
Gradle wouldn't pick the pinned versions in `buildSrc/.../conventions` for `api`

2022-05-19 13:38 UTC, bdw-g requested changes
Looks good, but, when I run this:
```
git clean -xdf
./bin/dwh-migration-dumper
```

Then I get the following:

```
wiegmans@nifftuk:~/Code/google/dwh-migration-tools$ ./bin/dwh-migration-dumper
+++ readlink -f ./bin/dwh-migration-dumper
++ dirname /usr/local/google/home/wiegmans/Code/google/dwh-migration-tools/bin/dwh-migration-dumper
+ BIN=/usr/local/google/home/wiegmans/Code/google/dwh-migration-tools/bin/../dumper/app/build/install/app/bin/dwh-migration-dumper
+ '[' '!' -x /usr/local/google/home/wiegmans/Code/google/dwh-migration-tools/bin/../dumper/app/build/install/app/bin/dwh-migration-dumper ']'
+ cd dumper
+ ./gradlew --parallel :app:installDist
./bin/dwh-migration-dumper: line 6: ./gradlew: No such file or directory
```

So there may be some further updates required

2022-05-20 14:21 UTC, bdw-g approved these changes
tested it and it works

2022-05-20 15:01 UTC, genemerrill approved these changes
works for me too

2022-05-20 17:30 UTC, shevek-google commented on build.gradle
> +            }
This will do, but for the future, I'm a bit nervous about an afterEvaluate.

2022-05-20 17:31 UTC, merged