add equality check for intervals
google/dwh-migration-tools pull request #190
Opened 2023-04-06 15:33 UTC by ishmum123

This would also be needed for #133

2023-04-06 15:47 UTC, dawidxc approved these changes

2023-04-06 15:47 UTC, dawidxc commented on dumper/app/src/test/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedIntervalTest.java
> +  public void test_equals_trueWhenStartAndEndTimeAreEqual() {
Optional: I would suggest to drop the `test_` prefix.

2023-04-06 15:47 UTC, dawidxc commented on dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedInterval.java
> +    return interval.getStart().isEqual(getStart())
nit: In the same class the fields can be accessed directly, i.e. `interval.start.isEqualTo(start)`.

2023-04-06 15:47 UTC, dawidxc commented on dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedInterval.java
> +    ZonedInterval interval = (ZonedInterval) obj;
nit: I would suggest to rename to `otherInterval`.

2023-04-07 09:31 UTC, paolomorandini requested changes

2023-04-07 09:31 UTC, paolomorandini commented on dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/ZonedInterval.java
> +  public boolean equals(Object obj) {
Please also implement `hashCode`.

2023-04-07 14:15 UTC, paolomorandini approved these changes

2023-04-07 14:32 UTC, merged