Display DMT on README.md
google/dwh-migration-tools pull request #302
Opened 2023-10-27 15:55 UTC by ishmum123

As requested by @zhaber

2023-10-27 15:59 UTC, zhaber commented
For an end-to-end BigQuery migration solution, use [Data Migration Tool (DMT)](https://github.com/GoogleCloudPlatform/data-migration-tool). DMT currently supports Redshift, TeraData, Hive, and Oracle as data sources and BigQuery as the destination.

2023-10-27 19:43 UTC, shevek-google requested changes
Could the DMT group please give us a demo before we approve this PR?

2023-10-27 20:24 UTC, zhaber commented
Added DMT demo to our Nov 1 meeting agenda

2023-10-27 20:31 UTC, shevek-google commented
> Added DMT demo to our Nov 1 meeting agenda

Could you invite me to that meeting, please? I don't see it. Also, can we please do a day when I'm in the office? I'm out on 1st Nov.

2023-12-13 10:29 UTC, dawidxc commented on README.md
> +DMT currently supports Redshift, TeraData, Hive, and Oracle as data sources and BigQuery as the destination.
nit: Teradata

2024-01-25 18:47 UTC, ishmum123 commented
@zhaber any updates on this?

2024-02-05 10:38 UTC, closed without merging

2024-02-05 10:39 UTC, ishmum123 commented
Closing due to no action

2024-02-06 00:32 UTC, zhaber commented
I believe @shevek-google is following up on this