Snowflake database flag fix
google/dwh-migration-tools pull request #333
Opened 2023-12-29 11:21 UTC by cyulysses-corp

1. Un-require database flag for Snowflake because it is not a necessary parameter. Still allowing providing database by the user, and will do database access check in this case.
2. Actually use the provided database to check, instead of using the wrong "current_databaase()" method.

2023-12-29 11:47 UTC, kpiotrowski requested changes
There are some format issues please run `./gradlew :dumper:app:spotlessApply` to fix it.

2023-12-29 13:50 UTC, cyulysses-corp commented
> There are some format issues please run `./gradlew :dumper:app:spotlessApply` to fix it.

Done.

2023-12-29 16:17 UTC, kpiotrowski approved these changes
LGTM 👍

2024-01-02 23:49 UTC, shevek-google submitted a review, later dismissed
This smells of a gateway to SQL injection. Are we sure we want to do this?

2024-01-03 10:02 UTC, cyulysses-corp commented
> This smells of a gateway to SQL injection. Are we sure we want to do this?

This app is meant to be used by the user who also has sufficient access to the database already, and this step does not bypass the credential validation. i.e. it is not the use cases where doing a direct SQL query to the database is harder than embedding it in a SQL injection attack.

If there are other use cases that you planned this app for but I do not know, and you think they are at risk, then I will happily put some SQL injection protection here.

2024-01-03 13:17 UTC, kpiotrowski commented
> > This smells of a gateway to SQL injection. Are we sure we want to do this?
> 
> This app is meant to be used by the user who also has sufficient access to the database already, and this step does not bypass the credential validation. i.e. it is not the use cases where doing a direct SQL query to the database is harder than embedding it in a SQL injection attack.
> 
> If there are other use cases that you planned this app for but I do not know, and you think they are at risk, then I will happily put some SQL injection protection here.

I tried to run Dumper with invalid database name and it fails at very beginning with credentials validation error. 
![image](https://github.com/google/dwh-migration-tools/assets/14976096/1077f583-1414-463a-9b98-d3b7dc2bd84a)

so the SQL injection is not possible here because of validation, but best practice would be avoid it by design. Can you provide databaseName as a parameter to the query? sth like:

```
String sql = "USE DATABASE ?";
return jdbcTemplate.queryForObject(sql, new Object[]{databaseName}, String.class);
```

2024-01-03 13:53 UTC, cyulysses-corp commented
> > > This smells of a gateway to SQL injection. Are we sure we want to do this?
> > 
> > 
> > This app is meant to be used by the user who also has sufficient access to the database already, and this step does not bypass the credential validation. i.e. it is not the use cases where doing a direct SQL query to the database is harder than embedding it in a SQL injection attack.
> > If there are other use cases that you planned this app for but I do not know, and you think they are at risk, then I will happily put some SQL injection protection here.
> 
> I tried to run Dumper with invalid database name and it fails at very beginning with credentials validation error. ![image](https://private-user-images.githubusercontent.com/14976096/293920055-1077f583-1414-463a-9b98-d3b7dc2bd84a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODgyMzQsIm5iZiI6MTcwNDI4NzkzNCwicGF0aCI6Ii8xNDk3NjA5Ni8yOTM5MjAwNTUtMTA3N2Y1ODMtMTQxNC00NjNhLTliOTgtZDNiN2RjMmJkODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEzMTg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYmMyMmUwNTIxZmRkMjM5NjgwOTlmZmE3MjA2YTQxYmFlZWVjODQ3NWQyMzY3NTYwNzgxOWNjNjA4YmExNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EgaIsJt11_EGHbeotP1u51zezp66Nm66uQqzu07Z2EU)
> 
> so the SQL injection is not possible here because of validation, but best practice would be avoid it by design. Can you provide databaseName as a parameter to the query? sth like:
> 
> ```
> String sql = "USE DATABASE ?";
> return jdbcTemplate.queryForObject(sql, new Object[]{databaseName}, String.class);
> ```

Thanks for weighing in. Actually I initially tried with the exact same way you suggested, but had to change to using explicit String.format for the sql query instead of jdbcTemplate(sql, requiredType, args) because args are not binded consistently. For example, this is the error message I got from that implementation:
```
********************************************************************
* ERROR
* PreparedStatementCallback; bad SQL grammar [USE DATABASE ?]; nested exception is net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 13 unexpected '?'.
* Caused by: SQL compilation error:
syntax error line 1 at position 13 unexpected '?'.
********************************************************************
```

I can implement custom SQL inspection to restrict the string inputs allowed here for sure, but I just was not sure about the necessity of it.

2024-01-03 21:13 UTC, shevek-google commented
Just because _we_ aren't (currently) deploying it in an injection-sensitive situation doesn't mean the customer isn't. But we should talk internally about the future.

However, given the proof that a ? isn't legal there, let's keep the quotes, sanitize the name to make sure it doesn't contain a quote, and then this is probably the best we can do. CharMatcher.anyMatch?

2024-01-05 16:29 UTC, cyulysses-corp commented
> Just because _we_ aren't (currently) deploying it in an injection-sensitive situation doesn't mean the customer isn't. But we should talk internally about the future.
> 
> However, given the proof that a ? isn't legal there, let's keep the quotes, sanitize the name to make sure it doesn't contain a quote, and then this is probably the best we can do. CharMatcher.anyMatch?

It turns out that a bad database name would already cause failure during the creation of the JdbcHandle, example:
```
    Jan 05, 2024 4:10:11 PM net.snowflake.client.jdbc.RestRequest execute
    SEVERE: Error response: HTTP Response code: 400, request: POST [https://compilerworks.snowflakecomputing.com:443/session/v1/login-request?databaseName=db12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890&warehouse=testwh&roleName=tester&requestId=1ea7f4f8-bf3e-4999-b58d-db0c5e56d760](https://compilerworks.snowflakecomputing.com/session/v1/login-request?databaseName=db12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890&warehouse=testwh&roleName=tester&requestId=1ea7f4f8-bf3e-4999-b58d-db0c5e56d760) HTTP/1.1
    Jan 05, 2024 4:10:11 PM net.snowflake.client.core.HttpUtil executeRequestInternal
    SEVERE: Error executing request: POST [https://compilerworks.snowflakecomputing.com:443/session/v1/login-request?databaseName=db12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890&warehouse=testwh&roleName=tester&requestId=1ea7f4f8-bf3e-4999-b58d-db0c5e56d760](https://compilerworks.snowflakecomputing.com/session/v1/login-request?databaseName=db12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890&warehouse=testwh&roleName=tester&requestId=1ea7f4f8-bf3e-4999-b58d-db0c5e56d760) HTTP/1.1
    Jan 05, 2024 4:10:11 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
    SEVERE: Response status line reason: Bad Request
    Jan 05, 2024 4:10:11 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
    SEVERE: Response content: Not a valid SQL Identifier.
```

Note that So the "USE DATABASE" will be redundant.

Snowflake driver also has intrinsic parsing that prevents trickery, but only because it parses it as a url.
```
    Jan 05, 2024 4:10:11 PM net.snowflake.client.jdbc.SnowflakeConnectString parse
    WARNING: Exception thrown while parsing Snowflake connect string. Illegal character in url.
```
It is actually kinda sad because no double quotes or unicode name is allowed.

I think the best way is for us to simply ignore --database flag for Snowflake connectors. i.e. we don't append "db=" with the database name even if the user specifies it.

2024-01-08 10:17 UTC, dawidxc approved these changes

2024-01-08 10:17 UTC, dawidxc commented on dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/snowflake/AbstractSnowflakeConnector.java
> +      checkCurrentDatabaseExists(arguments.getDatabases().get(0), jdbcHandle.getJdbcTemplate());
The method name `checkCurrentDatabaseExists` starts with `check`, even though it issues `USE DATABASE` that alters the JDBC session (i.e. it's not just a check). I would suggest to either rename the method or call 2 methods - one for checking that the database exists, another for setting the current database for the session.

2024-01-11 15:48 UTC, cyulysses-corp commented
> This smells of a gateway to SQL injection. Are we sure we want to do this?

PTAL. Thanks.

2024-01-12 13:39 UTC, merged