[b/356461225] Add HDFS progress logging
google/dwh-migration-tools pull request #534
Opened 2024-08-23 18:16 UTC by dawidxc

2024-08-26 10:25 UTC, misolt commented on dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/ScanContext.java
> +        .append("\n       num dirs walkd: " + numDirsWalked)
nit: walkd -> walked

2024-08-26 10:29 UTC, dawidxc commented on dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/ScanContext.java
> +        .append("\n       num dirs walkd: " + numDirsWalked)
Fixed.

2024-08-26 17:52 UTC, shevek-google requested changes
Could this use https://github.com/google/dwh-migration-tools/blob/main/dumper/lib-common/src/main/java/com/google/edwmigration/dumper/plugin/ext/jdk/progress/ConcurrentRecordProgressMonitor.java instead, particularly if the 'total' field was updated to be a mutable LongAdder? If we want an ETA, I think adding that to ConcurrentProgressMonitor would be a lovely feature update.

Note that System.currentTimeMillis() is a very expensive call, which does not show up in a stack-sampling profiler, because it's not a safepoint; BlockProgressMonitor is designed to reduce that overhead.

2024-08-26 17:52 UTC, shevek-google commented on dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/ScanContext.java
> +        .append(timeSpentInListStatus.getSeconds() + "s")
This should probably be a chained append(), not a String-+ in the middle, as that creates an extra StringBuilder and String.

2024-08-26 17:52 UTC, shevek-google commented on dumper/app/src/main/java/com/google/edwmigration/dumper/application/dumper/connector/hdfs/ScanContext.java
> +      partialProgressLogger.logProgress("HDFS scan " + percentFinished + "% completed");
A lot of this looks very similar to the shared/common code in [Concurrent]RecordProgressMonitor. Would it be possible to use that?

2024-12-16 11:05 UTC, vladislav-sidorovich commented
Actual PR is here https://github.com/google/dwh-migration-tools/pull/673

2025-03-24 09:53 UTC, closed without merging