Add language to functions.csv for Redshift
google/dwh-migration-tools pull request #56
Opened 2022-07-08 20:46 UTC by dawidxc

2022-07-08 20:48 UTC, shevek-google approved these changes

2022-07-08 20:49 UTC, shevek-google requested changes
Needs adding to the enum in the format description.

Add a field to 

https://github.com/google/dwh-migration-tools/blob/main/dumper/lib-dumper-spi/src/main/java/com/google/edwmigration/dumper/plugin/lib/dumper/spi/RedshiftMetadataDumpFormat.java#L174

2022-07-08 22:46 UTC, shevek-google approved these changes
I'll approve this because while I suspect the case mismatch in the header enum is still a bug, it's not a new bug, so you're not responsible for it.

2022-07-11 07:29 UTC, bdw-g approved these changes

2022-07-11 11:13 UTC, merged