Fix issue with --version flag outputting null
google/dwh-migration-tools pull request #84
Opened 2022-08-23 22:28 UTC by Hackerpilot

2022-08-25 22:52 UTC, shevek-google requested changes

2022-08-25 22:52 UTC, shevek-google commented on dumper/app/build.gradle
> +version = '1.0.8'
I think we don't want version or group here - version is specified at release-build time, and group is specified ... where? cc @paolomorandini for explicit review please

2022-08-29 18:17 UTC, shevek-google commented
You probably want to put the plugin on the classpath in buildSrc/build.gradle and apply the plugin in [dwh-migration-tools](https://github.com/google/dwh-migration-tools)/[buildSrc](https://github.com/google/dwh-migration-tools/tree/main/buildSrc)/[src](https://github.com/google/dwh-migration-tools/tree/main/buildSrc/src)/[main](https://github.com/google/dwh-migration-tools/tree/main/buildSrc/src/main)/[groovy](https://github.com/google/dwh-migration-tools/tree/main/buildSrc/src/main/groovy)/dwh-migration-dumper.java-common-conventions.gradle

2022-08-30 00:32 UTC, shevek-google approved these changes

2022-08-30 09:29 UTC, paolomorandini approved these changes

2022-08-30 14:41 UTC, merged